/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseconn;

import com.mysql.jdbc.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author c3
 */
public class BANKING_SYSTEM extends javax.swing.JFrame {

    /**
     * Creates new form BANKING_SYSTEM
     */
    public BANKING_SYSTEM() {
        initComponents();
    }
    int acc = 14603498;
    double bal = 10000;
    int serno = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        details = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        depositFund = new javax.swing.JButton();
        accNumber = new javax.swing.JTextField();
        withdraw = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        balance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LABE1 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Development Bank Of India ");
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentHidden(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 650, 130));

        logOut.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, 210, 30));

        jLabel2.setFont(jLabel2.getFont().deriveFont((jLabel2.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        jLabel2.setText("Available Balance ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 210, 40));

        name.setFont(name.getFont().deriveFont((name.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 190, 30));

        details.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        details.setText("Get Account Details ");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        getContentPane().add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 210, 30));

        jLabel3.setFont(jLabel3.getFont().deriveFont((jLabel3.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        jLabel3.setText("Enter Amount ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 40));

        depositFund.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        depositFund.setText("Deposite Funds");
        depositFund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositFundActionPerformed(evt);
            }
        });
        getContentPane().add(depositFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 210, 30));
        getContentPane().add(accNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 290, 40));

        withdraw.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        withdraw.setText("Withdraw ");
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        getContentPane().add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 210, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No.", "Particularsl", "Amount", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, -1, -1));

        balance.setFont(balance.getFont().deriveFont((balance.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        balance.setText("Account Number :");
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 210, 40));

        jLabel6.setFont(jLabel6.getFont().deriveFont((jLabel6.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        jLabel6.setText("Account Number :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 210, 40));

        LABE1.setFont(LABE1.getFont().deriveFont((LABE1.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        LABE1.setText("Name  :  ");
        getContentPane().add(LABE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 80, 30));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 290, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentHidden

    }//GEN-LAST:event_jLabel1ComponentHidden

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logOutActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        accNumber.setText("" + acc);
        balance.setText("" + bal);
        name.setText(" NITESH KR");

    }//GEN-LAST:event_detailsActionPerformed

    private void depositFundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositFundActionPerformed
        try {
            if (accNumber.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "amount cannot be empty  ");
                return;
            }
            if (Double.parseDouble(accNumber.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "invalid amount ");
                accNumber.setText("");
            }
            bal += Double.parseDouble(accNumber.getText());
            balance.setText("" + bal);
            JOptionPane.showMessageDialog(this, "funds deposited successfully  ");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{serno++, "deposit ", Double.parseDouble(accNumber.getText()), Double.parseDouble(balance.getText())});
            accNumber.setText(" ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "amount cannot be empty  execption is ");

        }
    }//GEN-LAST:event_depositFundActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        try {
            if (accNumber.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "amount cannot be empty  ");
                return;
            }
            if (Double.parseDouble(accNumber.getText()) > bal) {
                JOptionPane.showMessageDialog(this, "Not enough balance try again ");
                accNumber.setText("");
            }
            bal -= Double.parseDouble(accNumber.getText());
            balance.setText("" + bal);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{serno++, "withdraw ", Double.parseDouble(accNumber.getText()), Double.parseDouble(balance.getText())});
            accNumber.setText(" ");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_withdrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        
        
        
        
        
        
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BANKING_SYSTEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BANKING_SYSTEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BANKING_SYSTEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BANKING_SYSTEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BANKING_SYSTEM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABE1;
    private javax.swing.JTextField accNumber;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel balance;
    private javax.swing.JButton depositFund;
    private javax.swing.JButton details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel name;
    private javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables
}
